services:
- type: web
  name: rag-backend
  env: python
  region: oregon
  plan: starter-plus
  autoDeploy: true
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
  envVars:
    - key: OPENAI_API_KEY
      sync: false
    - key: ANTHROPIC_API_KEY
      sync: false
    - key: PINECONE_API_KEY
      sync: false
    - key: REDIS_URL
      sync: false
    - key: PINECONE_INDEX_NAME
      value: your-pinecone-index
